# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{halo-reach-api}
  s.version = "1.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{David Czarnecki}]
  s.date = %q{2011-08-18}
  s.description = %q{Ruby gem for interacting with the Halo:Reach API}
  s.email = %q{dczarnecki@agoragames.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "halo-reach-api.gemspec",
    "lib/halo-reach-api.rb",
    "lib/halo-reach-util.rb",
    "test/fakeweb/get_current_challenges.json",
    "test/fakeweb/get_file_details.json",
    "test/fakeweb/get_game_details.json",
    "test/fakeweb/get_game_history.json",
    "test/fakeweb/get_game_metadata.json",
    "test/fakeweb/get_player_details_with_no_stats.json",
    "test/fakeweb/get_player_details_with_stats_by_map.json",
    "test/fakeweb/get_player_details_with_stats_by_playlist.json",
    "test/fakeweb/get_player_file_set_files.json",
    "test/fakeweb/get_player_file_sets.json",
    "test/fakeweb/get_player_file_share.json",
    "test/fakeweb/get_player_recent_screenshots.json",
    "test/fakeweb/get_player_rendered_videos.json",
    "test/fakeweb/reach_file_search.json",
    "test/helper.rb",
    "test/test_halo-reach-api.rb",
    "test/test_halo-reach-util.rb"
  ]
  s.homepage = %q{http://github.com/agoragames/halo-reach-api}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Ruby gem for interacting with the Halo:Reach API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, ["= 0.9.9"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, ["= 0.9.9"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, ["= 0.9.9"])
  end
end

